#define MATERIAL_ARAMIND     ["ARAMIND",   0.25]
#define MATERIAL_UHMWPE      ["UHMWPE",    0.45]
#define MATERIAL_COMBINED    ["COMBINED",  0.50]
#define MATERIAL_TITAN       ["TITAN",     0.55]
#define MATERIAL_STEEL       ["STEEL",     0.70]
#define MATERIAL_CERAMIC     ["CERAMIC",   0.80]

#define METERIALLIST         [MATERIAL_ARAMIND, MATERIAL_UHMWPE, MATERIAL_COMBINED, MATERIAL_TITAN, MATERIAL_STEEL, MATERIAL_CERAMIC]
#define ALLOWFIXMETERIALLIST [                  MATERIAL_UHMWPE, MATERIAL_COMBINED, MATERIAL_TITAN, MATERIAL_STEEL, MATERIAL_CERAMIC]